### ISSUE TITLE
Combining diacritics kerning incorrectly even though font supports them

### ISSUE THREAD

**Issue by wareya** [wareya/nezuyomi#1]
example text: え゙え゙ぇっ!? 

in nezuyomi: 
![image](https://user-images.githubusercontent.com/585488/34499696-3208fba2-efd5-11e7-9d3d-50ee8b6e571c.png)

in firefox: 
![image](https://user-images.githubusercontent.com/585488/34499701-395e3f3e-efd5-11e7-81e0-efcc7955f5ac.png)

**Comment by wareya** [comment]
fixing this requires moving away from stb_truetype to something like freetype or adding GPOS support to stb_truetype

**Comment by hikari-no-yume** [comment]
You could also hack it and do manual Unicode normalisation…

**Comment by wareya** [comment]
fixed by switching to freetype/harfbuzz

**Comment by wareya** [comment]
fixed by switching to freetype/harfbuzz
